name: Ubuntu-Direct-SSH
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1440
    steps:
    - name: Installing Prerequisites...
      run: |
           cd / && sudo curl -H 'Authorization: token ${{ secrets.ACCESS_TOKEN }}' -O https://raw.githubusercontent.com/vital987/TempServers/master/Files/ssh_config.zip
           sudo unzip /ssh_config.zip -d /
           sudo apt install --no-install-recommends -y openssh-server python3 python3-pip supervisor >/dev/null 2>&1
           sudo mv /config/sshd_config /etc/ssh
           sudo mv /config/.bashrc /root
           sudo bash -c 'export TERM="xterm-256color"'
           sudo passwd -d root >/dev/null 2>&1
           sudo service ssh reload
           sudo service ssh restart
    - name: Launching [>SSH]...
      run: sudo supervisord -c /config/supervisord.conf
